# Generated by Django 4.2.7 on 2025-06-03 09:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_remove_expenseform_form_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenseform',
            name='attachment',
            field=models.FileField(blank=True, null=True, storage='expenses.storage.OneDriveStorage', upload_to='expense_attachments/'),
        ),
        migrations.AlterField(
            model_name='expensetitle',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
