# Generated by Django 4.2.7 on 2025-06-03 09:24

from django.db import migrations, models
import expenses.storage


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_alter_expenseform_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenseform',
            name='attachment',
            field=models.FileField(blank=True, null=True, storage=expenses.storage.OneDriveStorage(), upload_to='expense_attachments/'),
        ),
    ]
