# Generated by Django 4.2.7 on 2025-06-04 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_alter_expenseform_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenseform',
            name='currency',
            field=models.CharField(choices=[('CAD', 'Canadian Dollar'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('INR', 'Indian Rupee')], max_length=3),
        ),
    ]
