# Generated by Django 5.0.14 on 2025-06-13 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0006_alter_expenseform_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenseform',
            name='amount',
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
    ]
