# Generated by Django 4.2.7 on 2025-06-17 06:50

from django.db import migrations, models
import expenses.storage


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0008_alter_expenseform_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.RenameField(
            model_name='expenseform',
            old_name='attachment',
            new_name='attachment1',
        ),
        migrations.AddField(
            model_name='expenseform',
            name='attachment2',
            field=models.FileField(blank=True, null=True, storage=expenses.storage.OneDriveStorage(), upload_to='expense_attachments/'),
        ),
    ]
