# Generated by Django 4.2.7 on 2025-06-17 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0009_alter_user_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expenseform',
            old_name='attachment1',
            new_name='attachment',
        ),
        migrations.RemoveField(
            model_name='expenseform',
            name='attachment2',
        ),
    ]
