# Generated by Django 4.2.7 on 2025-06-17 08:57

from django.db import migrations, models
import expenses.storage


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0010_rename_attachment1_expenseform_attachment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expenseform',
            old_name='attachment',
            new_name='attachment1',
        ),
        migrations.AddField(
            model_name='expenseform',
            name='attachment2',
            field=models.FileField(blank=True, null=True, storage=expenses.storage.OneDriveStorage(), upload_to='expense_attachments/'),
        ),
        migrations.AlterField(
            model_name='expenseform',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=19),
        ),
    ]
