# Generated by Django 4.2.7 on 2025-06-18 12:50

from django.db import migrations, models
import expenses.storage


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0012_remove_expenseform_attachment1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenseform',
            name='attachment1',
            field=models.FileField(blank=True, null=True, storage=expenses.storage.OneDriveStorage(), upload_to='expense_attachments/'),
        ),
        migrations.AddField(
            model_name='expenseform',
            name='attachment2',
            field=models.FileField(blank=True, null=True, storage=expenses.storage.OneDriveStorage(), upload_to='expense_attachments/'),
        ),
        migrations.DeleteModel(
            name='ExpenseAttachment',
        ),
    ]
