# Generated by Django 4.2.7 on 2025-06-18 13:27

from django.db import migrations, models
import django.db.models.deletion
import expenses.storage


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0013_expenseform_attachment1_expenseform_attachment2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenseform',
            name='attachment1',
        ),
        migrations.RemoveField(
            model_name='expenseform',
            name='attachment2',
        ),
        migrations.CreateModel(
            name='ExpenseAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=expenses.storage.OneDriveStorage(), upload_to='expense_attachments/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('expense_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='expenses.expenseform')),
            ],
        ),
    ]
