# Generated by Django 4.2.7 on 2025-06-19 08:46

from django.db import migrations, models
import expenses.storage


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0014_remove_expenseform_attachment1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenseattachment',
            name='original_filename',
            field=models.CharField(default='unknown', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expenseattachment',
            name='file',
            field=models.FileField(storage=expenses.storage.OneDriveStorage(), upload_to='temp_uploads/'),
        ),
    ]
