# Generated by Django 4.2.7 on 2025-06-19 09:01

from django.db import migrations, models
import expenses.storage


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0015_expenseattachment_original_filename_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenseattachment',
            name='original_filename',
        ),
        migrations.AlterField(
            model_name='expenseattachment',
            name='file',
            field=models.FileField(storage=expenses.storage.OneDriveStorage(), upload_to='expense_attachments/'),
        ),
    ]
