# Generated by Django 4.2.7 on 2025-06-27 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0016_remove_expenseattachment_original_filename_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenseform',
            name='session_id',
            field=models.CharField(blank=True, help_text='Session ID for anonymous users', max_length=100, null=True),
        ),
    ]
