# Generated by Django 4.2.7 on 2025-06-27 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0017_expenseform_session_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenseform',
            name='session_id',
        ),
    ]
