# Generated by Django 4.2.7 on 2025-06-27 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0018_remove_expenseform_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenseform',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SEND_FOR_APPROVAL', 'Send for Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
    ]
