# Generated by Django 4.2.7 on 2025-07-08 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0019_alter_expenseform_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenseattachment',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
