# Generated by Django 4.2.7 on 2025-07-08 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0020_expenseattachment_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenseattachment',
            name='deleted',
        ),
    ]
